{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "titlis.fullname" . }}
  labels:
    {{- include "titlis.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [pods, services, configmaps, events]
    verbs: [get, list, watch, create, update, patch, delete]

  - apiGroups: ["apps"]
    resources: [deployments, deployments/status, replicasets, statefulsets]
    verbs: [get, list, watch]

  - apiGroups: ["autoscaling"]
    resources: [horizontalpodautoscalers, horizontalpodautoscalers/status]
    verbs: [get, list, watch, create, update, patch, delete]

  - apiGroups: ["networking.k8s.io"]
    resources: [ingresses]
    verbs: [get, list, watch]

  - apiGroups: ["policy"]
    resources: [poddisruptionbudgets]
    verbs: [get, list, watch]

  - apiGroups: ["titlis.io"]
    resources:
      - appscorecards
      - appscorecards/status
      - appremediations
      - appremediations/status
      - sloconfigs
      - sloconfigs/status
    verbs: [get, list, watch, create, update, patch, delete]

  - apiGroups: ["coordination.k8s.io"]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]

  - apiGroups: [""]
    resources: [namespaces]
    verbs: [get, list, watch]

  - apiGroups: [""]
    resources: [nodes]
    verbs: [list]

  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "titlis.fullname" . }}
  labels:
    {{- include "titlis.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "titlis.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "titlis.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
{{- end }}
