//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// --- AppScorecard ---

func (in *AppScorecard) DeepCopyInto(out *AppScorecard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *AppScorecard) DeepCopy() *AppScorecard {
	if in == nil {
		return nil
	}
	out := new(AppScorecard)
	in.DeepCopyInto(out)
	return out
}

func (in *AppScorecard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AppScorecardList) DeepCopyInto(out *AppScorecardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppScorecard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AppScorecardList) DeepCopy() *AppScorecardList {
	if in == nil {
		return nil
	}
	out := new(AppScorecardList)
	in.DeepCopyInto(out)
	return out
}

func (in *AppScorecardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AppScorecardStatus) DeepCopyInto(out *AppScorecardStatus) {
	*out = *in
	if in.OverallScore != nil {
		x := *in.OverallScore
		out.OverallScore = &x
	}
	if in.Pillars != nil {
		in, out := &in.Pillars, &out.Pillars
		*out = make([]PillarResult, len(*in))
		copy(*out, *in)
	}
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]FindingResult, len(*in))
		copy(*out, *in)
	}
	if in.Remediation != nil {
		in, out := &in.Remediation, &out.Remediation
		*out = new(RemediationInfo)
		**out = **in
	}
	if in.LastNotification != nil {
		in, out := &in.LastNotification, &out.LastNotification
		*out = (*in).DeepCopy()
	}
	if in.LastEvaluatedAt != nil {
		in, out := &in.LastEvaluatedAt, &out.LastEvaluatedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// --- AppRemediation ---

func (in *AppRemediation) DeepCopyInto(out *AppRemediation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *AppRemediation) DeepCopy() *AppRemediation {
	if in == nil {
		return nil
	}
	out := new(AppRemediation)
	in.DeepCopyInto(out)
	return out
}

func (in *AppRemediation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AppRemediationList) DeepCopyInto(out *AppRemediationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppRemediation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AppRemediationList) DeepCopy() *AppRemediationList {
	if in == nil {
		return nil
	}
	out := new(AppRemediationList)
	in.DeepCopyInto(out)
	return out
}

func (in *AppRemediationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AppRemediationSpec) DeepCopyInto(out *AppRemediationSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.IssuesFixed != nil {
		in, out := &in.IssuesFixed, &out.IssuesFixed
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *AppRemediationStatus) DeepCopyInto(out *AppRemediationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// --- SLOConfig ---

func (in *SLOConfig) DeepCopyInto(out *SLOConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *SLOConfig) DeepCopy() *SLOConfig {
	if in == nil {
		return nil
	}
	out := new(SLOConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *SLOConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SLOConfigList) DeepCopyInto(out *SLOConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SLOConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *SLOConfigList) DeepCopy() *SLOConfigList {
	if in == nil {
		return nil
	}
	out := new(SLOConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *SLOConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SLOConfigSpec) DeepCopyInto(out *SLOConfigSpec) {
	*out = *in
	if in.AppFramework != nil {
		x := *in.AppFramework
		out.AppFramework = &x
	}
	if in.Warning != nil {
		x := *in.Warning
		out.Warning = &x
	}
	if in.Numerator != nil {
		x := *in.Numerator
		out.Numerator = &x
	}
	if in.Denominator != nil {
		x := *in.Denominator
		out.Denominator = &x
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *SLOConfigStatus) DeepCopyInto(out *SLOConfigStatus) {
	*out = *in
	if in.SLOID != nil {
		x := *in.SLOID
		out.SLOID = &x
	}
	if in.LastSync != nil {
		in, out := &in.LastSync, &out.LastSync
		*out = (*in).DeepCopy()
	}
	if in.Error != nil {
		x := *in.Error
		out.Error = &x
	}
	if in.DetectedFramework != nil {
		x := *in.DetectedFramework
		out.DetectedFramework = &x
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
